I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/imaginary_friends_variables.rpy", line 27, in script
    define font_regular = gui_path("SongMyung-Regular.ttf")
  File "game/imaginary_friends_variables.rpy", line 27, in script
    define font_regular = gui_path("SongMyung-Regular.ttf")
  File "game/imaginary_friends_variables.rpy", line 27, in <module>
    define font_regular = gui_path("SongMyung-Regular.ttf")
TypeError: 'str' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/imaginary_friends_variables.rpy", line 27, in script
    define font_regular = gui_path("SongMyung-Regular.ttf")
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/imaginary_friends_variables.rpy", line 27, in script
    define font_regular = gui_path("SongMyung-Regular.ttf")
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\ast.py", line 2441, in execute
    self.set()
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\ast.py", line 2455, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/imaginary_friends_variables.rpy", line 27, in <module>
    define font_regular = gui_path("SongMyung-Regular.ttf")
TypeError: 'str' object is not callable

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Imaginary Friends 1.0
Sun Apr  2 12:44:58 2023
